# Generated by Django 5.2.2 on 2025-06-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_extracted_customer_gstin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="extracted_customer_gstin",
            new_name="buyer_gstin",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="extracted_date",
            new_name="invoice_date",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="extracted_supplier_gstin",
            new_name="seller_gstin",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="extracted_total_amount",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="extracted_invoice_number",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="cess_amount",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="cess_rate",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="cgst_rate",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="igst_rate",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="sgst_rate",
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_tax_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_taxable_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="cgst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="hsn_sac",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="igst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="sgst_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="taxable_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
