# Generated by Django 5.2.2 on 2025-06-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0003_rename_extracted_customer_gstin_invoice_buyer_gstin_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="total_amount",
            new_name="grand_total",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="total_tax_amount",
            new_name="total_tax",
        ),
        migrations.RenameField(
            model_name="lineitem",
            old_name="cgst_amount",
            new_name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_taxable_value",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="igst_amount",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="sgst_amount",
        ),
        migrations.RemoveField(
            model_name="lineitem",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ocr_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="tax_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="lineitem",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="taxable_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
