# Generated by Django 5.2.2 on 2025-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_rename_total_amount_invoice_grand_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing_ocr", "Processing OCR"),
                    ("ocr_completed", "OCR Completed"),
                    ("parsing_data", "Parsing Data"),
                    ("data_parsed", "Data Parsed"),
                    ("reconciliation_pending", "Reconciliation Pending"),
                    ("reconciliation_complete", "Reconciliation Complete"),
                    ("reconciliation_failed", "Reconciliation Failed"),
                ],
                default="uploaded",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("parsed", "Parsed"),
                    ("failed", "Failed"),
                    ("reconciled", "Reconciled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
